/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonsterMonsterIdRouteImport } from './routes/monster.$monsterId'

const MonstersLazyRouteImport = createFileRoute('/monsters')()
const AdoptLazyRouteImport = createFileRoute('/adopt')()
const IndexLazyRouteImport = createFileRoute('/')()

const MonstersLazyRoute = MonstersLazyRouteImport.update({
  id: '/monsters',
  path: '/monsters',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/monsters.lazy').then((d) => d.Route))
const AdoptLazyRoute = AdoptLazyRouteImport.update({
  id: '/adopt',
  path: '/adopt',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/adopt.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const MonsterMonsterIdRoute = MonsterMonsterIdRouteImport.update({
  id: '/monster/$monsterId',
  path: '/monster/$monsterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/adopt': typeof AdoptLazyRoute
  '/monsters': typeof MonstersLazyRoute
  '/monster/$monsterId': typeof MonsterMonsterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/adopt': typeof AdoptLazyRoute
  '/monsters': typeof MonstersLazyRoute
  '/monster/$monsterId': typeof MonsterMonsterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/adopt': typeof AdoptLazyRoute
  '/monsters': typeof MonstersLazyRoute
  '/monster/$monsterId': typeof MonsterMonsterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adopt' | '/monsters' | '/monster/$monsterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adopt' | '/monsters' | '/monster/$monsterId'
  id: '__root__' | '/' | '/adopt' | '/monsters' | '/monster/$monsterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdoptLazyRoute: typeof AdoptLazyRoute
  MonstersLazyRoute: typeof MonstersLazyRoute
  MonsterMonsterIdRoute: typeof MonsterMonsterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/monsters': {
      id: '/monsters'
      path: '/monsters'
      fullPath: '/monsters'
      preLoaderRoute: typeof MonstersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adopt': {
      id: '/adopt'
      path: '/adopt'
      fullPath: '/adopt'
      preLoaderRoute: typeof AdoptLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monster/$monsterId': {
      id: '/monster/$monsterId'
      path: '/monster/$monsterId'
      fullPath: '/monster/$monsterId'
      preLoaderRoute: typeof MonsterMonsterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdoptLazyRoute: AdoptLazyRoute,
  MonstersLazyRoute: MonstersLazyRoute,
  MonsterMonsterIdRoute: MonsterMonsterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
