/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonsterMonsterIdRouteImport } from './routes/monster.$monsterId'

const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonsterMonsterIdRoute = MonsterMonsterIdRouteImport.update({
  id: '/monster/$monsterId',
  path: '/monster/$monsterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/collection': typeof CollectionRoute
  '/gallery': typeof GalleryRoute
  '/guestbook': typeof GuestbookRoute
  '/monster/$monsterId': typeof MonsterMonsterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/collection': typeof CollectionRoute
  '/gallery': typeof GalleryRoute
  '/guestbook': typeof GuestbookRoute
  '/monster/$monsterId': typeof MonsterMonsterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/collection': typeof CollectionRoute
  '/gallery': typeof GalleryRoute
  '/guestbook': typeof GuestbookRoute
  '/monster/$monsterId': typeof MonsterMonsterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/collection'
    | '/gallery'
    | '/guestbook'
    | '/monster/$monsterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/collection'
    | '/gallery'
    | '/guestbook'
    | '/monster/$monsterId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/collection'
    | '/gallery'
    | '/guestbook'
    | '/monster/$monsterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CollectionRoute: typeof CollectionRoute
  GalleryRoute: typeof GalleryRoute
  GuestbookRoute: typeof GuestbookRoute
  MonsterMonsterIdRoute: typeof MonsterMonsterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monster/$monsterId': {
      id: '/monster/$monsterId'
      path: '/monster/$monsterId'
      fullPath: '/monster/$monsterId'
      preLoaderRoute: typeof MonsterMonsterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CollectionRoute: CollectionRoute,
  GalleryRoute: GalleryRoute,
  GuestbookRoute: GuestbookRoute,
  MonsterMonsterIdRoute: MonsterMonsterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
